### ISSUE TITLE
是否应该添加用户设置代理的功能呢

### ISSUE THREAD

**Issue by MoonShadowIllusion** [ifacker/chatGPT_terminal#2]
如题

**Comment by MoonShadowIllusion** [comment]
```NewClient```时，传入```func WithHTTPClient(httpClient *httpClient) ClientOption```，应该可以做到

https://pkg.go.dev/github.com/PullRequestInc/go-gpt3#NewClient

**Comment by ifacker** [comment]
这个API接口会用到代理吗？我暂时好像没发现API接口被墙的情况，你这边有这种情况吗？如果有这种情况，倒是可以考虑加一个代理模块

**Comment by MoonShadowIllusion** [comment]
那没事了
